version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./ecommerce/:/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.sample
    
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-home:/var/jenkins_home

volumes:
  jenkins-home: